(cl:defpackage my_package-srv
  (:use )
  (:export
   "SETROTATIONMATRIX"
   "<SETROTATIONMATRIX-REQUEST>"
   "SETROTATIONMATRIX-REQUEST"
   "<SETROTATIONMATRIX-RESPONSE>"
   "SETROTATIONMATRIX-RESPONSE"
  ))

