// Generated by gencpp from file my_package/SetRotationMatrixResponse.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_SETROTATIONMATRIXRESPONSE_H
#define MY_PACKAGE_MESSAGE_SETROTATIONMATRIXRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_package
{
template <class ContainerAllocator>
struct SetRotationMatrixResponse_
{
  typedef SetRotationMatrixResponse_<ContainerAllocator> Type;

  SetRotationMatrixResponse_()
    : theta(0.0)
    , K()  {
    }
  SetRotationMatrixResponse_(const ContainerAllocator& _alloc)
    : theta(0.0)
    , K(_alloc)  {
  (void)_alloc;
    }



   typedef float _theta_type;
  _theta_type theta;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _K_type;
  _K_type K;





  typedef boost::shared_ptr< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetRotationMatrixResponse_

typedef ::my_package::SetRotationMatrixResponse_<std::allocator<void> > SetRotationMatrixResponse;

typedef boost::shared_ptr< ::my_package::SetRotationMatrixResponse > SetRotationMatrixResponsePtr;
typedef boost::shared_ptr< ::my_package::SetRotationMatrixResponse const> SetRotationMatrixResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_package::SetRotationMatrixResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_package::SetRotationMatrixResponse_<ContainerAllocator1> & lhs, const ::my_package::SetRotationMatrixResponse_<ContainerAllocator2> & rhs)
{
  return lhs.theta == rhs.theta &&
    lhs.K == rhs.K;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_package::SetRotationMatrixResponse_<ContainerAllocator1> & lhs, const ::my_package::SetRotationMatrixResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d121ffca72fb4825b28080072009a7f5";
  }

  static const char* value(const ::my_package::SetRotationMatrixResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd121ffca72fb4825ULL;
  static const uint64_t static_value2 = 0xb28080072009a7f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_package/SetRotationMatrixResponse";
  }

  static const char* value(const ::my_package::SetRotationMatrixResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 theta\n"
"float32[] K\n"
;
  }

  static const char* value(const ::my_package::SetRotationMatrixResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta);
      stream.next(m.K);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRotationMatrixResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_package::SetRotationMatrixResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_package::SetRotationMatrixResponse_<ContainerAllocator>& v)
  {
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "K[]" << std::endl;
    for (size_t i = 0; i < v.K.size(); ++i)
    {
      s << indent << "  K[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.K[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_SETROTATIONMATRIXRESPONSE_H
