// Generated by gencpp from file my_package/SetRotationMatrix.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_SETROTATIONMATRIX_H
#define MY_PACKAGE_MESSAGE_SETROTATIONMATRIX_H

#include <ros/service_traits.h>


#include <my_package/SetRotationMatrixRequest.h>
#include <my_package/SetRotationMatrixResponse.h>


namespace my_package
{

struct SetRotationMatrix
{

typedef SetRotationMatrixRequest Request;
typedef SetRotationMatrixResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRotationMatrix
} // namespace my_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_package::SetRotationMatrix > {
  static const char* value()
  {
    return "e26b0831b5184f4a3c0b59f189c892e6";
  }

  static const char* value(const ::my_package::SetRotationMatrix&) { return value(); }
};

template<>
struct DataType< ::my_package::SetRotationMatrix > {
  static const char* value()
  {
    return "my_package/SetRotationMatrix";
  }

  static const char* value(const ::my_package::SetRotationMatrix&) { return value(); }
};


// service_traits::MD5Sum< ::my_package::SetRotationMatrixRequest> should match
// service_traits::MD5Sum< ::my_package::SetRotationMatrix >
template<>
struct MD5Sum< ::my_package::SetRotationMatrixRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_package::SetRotationMatrix >::value();
  }
  static const char* value(const ::my_package::SetRotationMatrixRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_package::SetRotationMatrixRequest> should match
// service_traits::DataType< ::my_package::SetRotationMatrix >
template<>
struct DataType< ::my_package::SetRotationMatrixRequest>
{
  static const char* value()
  {
    return DataType< ::my_package::SetRotationMatrix >::value();
  }
  static const char* value(const ::my_package::SetRotationMatrixRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_package::SetRotationMatrixResponse> should match
// service_traits::MD5Sum< ::my_package::SetRotationMatrix >
template<>
struct MD5Sum< ::my_package::SetRotationMatrixResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_package::SetRotationMatrix >::value();
  }
  static const char* value(const ::my_package::SetRotationMatrixResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_package::SetRotationMatrixResponse> should match
// service_traits::DataType< ::my_package::SetRotationMatrix >
template<>
struct DataType< ::my_package::SetRotationMatrixResponse>
{
  static const char* value()
  {
    return DataType< ::my_package::SetRotationMatrix >::value();
  }
  static const char* value(const ::my_package::SetRotationMatrixResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_SETROTATIONMATRIX_H
